name: run-tests
on: [pull_request]
jobs:
  drive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: subosito/flutter-action@v1
    - run: dart analyze
    - run: flutter test
